### ISSUE TITLE
Crash homebridge

### ISSUE THREAD

**Issue by shaboli** [mmende/homebridge-samsungtv-control#10]
when turning off the tv i receive this:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/index.js:99:5
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote/lib/samsung-remote.js:94:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mmende** [comment]
Hi,

I don't really see why the callback is being called twice but I encapsulated the callback functions into a "DisposableCallback" that should prevent calling the callback multiple times. Hopefully this fixes the problem for you.

Kind regards
