### ISSUE TITLE
Homebridge won't start with this plugin.

### ISSUE THREAD

**Issue by krzysiej** [mmende/homebridge-samsungtv-control#22]
Hi, 
I got this error when I installed this plugin and configure it as in the example.
Latest Homebridge 1.1.1
I'm newbie...
Before this samsungtv-control plugin I installed Xiaomi Air Purifier2 and Desk Lamp2 and it worked fine.

I've got Samsung SmartTV UE55F6770 2013

Error loading accessory requested in your config.json at position 2
[6/30/2020, 00:26:37] Error: The requested accessory 'SamsungTV' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)

**Comment by mmende** [comment]
The plugin has been reimplemented completely and can be found [here](https://github.com/mmende/homebridge-samsungtv-control2) now. I am closing all issues in this repository therefore. Please consider testing the new plugin and help me improve it.
